# Site settings
title: Are we free* yet?
email: augustin.trancart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This website references each popular type of devices alongside whether or not we can run open-source and ultimately free softwares.
baseurl: "" 
url: "http://arewefreeyet.org/"
twitter_username: autra42
github_username: autra

# Build settings
markdown: kramdown
